import Footer from '@components/Footer';
import './globals.css'
import Header from '@components/Header'
import Login from '@components/Login'


export const metadata = {
  title: 'E-Doc',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const loginFlag = true;
  return (
    <html lang="en">
      <body className="min-h-screen overflow-x-hidden">
        {loginFlag ? (
          <>
            <Header />
            {children}
          </>
        ) : (
          <Login />
        )}
        {<Footer />}
      </body>
    </html>
  )
}
